// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDOEJ54Q9iW0HE9tBZfHLiNJQE2Zkntl-o',
    appId: '1:902199430301:web:0a72d69f8829478c015874',
    messagingSenderId: '902199430301',
    projectId: 'weatherapp-53107',
    authDomain: 'weatherapp-53107.firebaseapp.com',
    storageBucket: 'weatherapp-53107.appspot.com',
    measurementId: 'G-DTSX9DG6D0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBLGtLM2-c3YeQ32D0pRBwYh4trzCYU6xo',
    appId: '1:902199430301:android:83d221f000e838d6015874',
    messagingSenderId: '902199430301',
    projectId: 'weatherapp-53107',
    storageBucket: 'weatherapp-53107.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB4e5VkStKgd1UDYNHulacCma_ugR-tIOE',
    appId: '1:902199430301:ios:3e1a29309dcad2fa015874',
    messagingSenderId: '902199430301',
    projectId: 'weatherapp-53107',
    storageBucket: 'weatherapp-53107.appspot.com',
    iosBundleId: 'com.example.weather',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB4e5VkStKgd1UDYNHulacCma_ugR-tIOE',
    appId: '1:902199430301:ios:0ee5fd6d3fdd1f38015874',
    messagingSenderId: '902199430301',
    projectId: 'weatherapp-53107',
    storageBucket: 'weatherapp-53107.appspot.com',
    iosBundleId: 'com.example.weather.RunnerTests',
  );
}
